---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
        name: wordpress-stag-pvc
        namespace: stag
spec: 
        accessModes: 
                - ReadWriteOnce
        resources: 
                requests: 
                         storage: 8Gi
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#        name: pesbuk-stag-pvc
#        namespace: stag
#spec:
#        storageClassName: standard
#        accessModes:
#                - ReadWriteOnce
#        resources:
#                requests:
#                        storage: 8Gi
