apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
        name: landing-page
        namespace: prod
        labels:
                app: landing-page
spec:
        selector:
                matchLabels:
                        app: landing-page
        replicas: 2 # tells deployment to run 2 pods matching the template
        template: # create pods using pod definition in this template
                metadata:
                        labels:
                                app: landing-page
                spec:
                        containers:
                                - name: landing-page
                                  image: ikhsannugs/landing-page
                                  ports:
                                          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
        name: landing-page-prod
        namespace: prod
        labels:
                app: landing-page
spec:
        type: NodePort
        selector:
                app: landing-page
        ports:
                - port: 80
                  protocol: TCP
                  targetPort: 80
